/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { StudyMaterial } from "./StudyMaterial";
import { StudyMaterialCountArgs } from "./StudyMaterialCountArgs";
import { StudyMaterialFindManyArgs } from "./StudyMaterialFindManyArgs";
import { StudyMaterialFindUniqueArgs } from "./StudyMaterialFindUniqueArgs";
import { CreateStudyMaterialArgs } from "./CreateStudyMaterialArgs";
import { UpdateStudyMaterialArgs } from "./UpdateStudyMaterialArgs";
import { DeleteStudyMaterialArgs } from "./DeleteStudyMaterialArgs";
import { StudyMaterialService } from "../studyMaterial.service";
@graphql.Resolver(() => StudyMaterial)
export class StudyMaterialResolverBase {
  constructor(protected readonly service: StudyMaterialService) {}

  async _studyMaterialsMeta(
    @graphql.Args() args: StudyMaterialCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [StudyMaterial])
  async studyMaterials(
    @graphql.Args() args: StudyMaterialFindManyArgs
  ): Promise<StudyMaterial[]> {
    return this.service.studyMaterials(args);
  }

  @graphql.Query(() => StudyMaterial, { nullable: true })
  async studyMaterial(
    @graphql.Args() args: StudyMaterialFindUniqueArgs
  ): Promise<StudyMaterial | null> {
    const result = await this.service.studyMaterial(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => StudyMaterial)
  async createStudyMaterial(
    @graphql.Args() args: CreateStudyMaterialArgs
  ): Promise<StudyMaterial> {
    return await this.service.createStudyMaterial({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => StudyMaterial)
  async updateStudyMaterial(
    @graphql.Args() args: UpdateStudyMaterialArgs
  ): Promise<StudyMaterial | null> {
    try {
      return await this.service.updateStudyMaterial({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => StudyMaterial)
  async deleteStudyMaterial(
    @graphql.Args() args: DeleteStudyMaterialArgs
  ): Promise<StudyMaterial | null> {
    try {
      return await this.service.deleteStudyMaterial(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
